# Generated by Django 5.0.4 on 2024-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_the_comapny',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
