# Generated by Django 5.0.4 on 2024-06-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_about_the_comapny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_the_company',
            field=models.TextField(default='About Your Company'),
        ),
    ]
