# Generated by Django 5.0.4 on 2024-06-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_upload_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
    ]
